[package]
name = "ShellGame"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.29.0"
strum = "0.27.1"
strum_macros = "0.27.1"
uuid = { version = "1.16.0", features = ["v4"] }
